### ISSUE TITLE
Release driver_base for indigo

### ISSUE THREAD

**Issue by scpeters** [ros-drivers/driver_common#5]
It was mentioned in this [ros-release thread](http://lists.ros.org/pipermail/ros-release/2014-April/004391.html) that driver_base would be released for indigo once it was no longer blocked by diagnostics. Since diagnostics has been released, I believe driver_base is unblocked.

**Comment by chadrockey** [comment]
Done.

https://github.com/ros/rosdistro/pull/3974

**Comment by jack-oquin** [comment]
Thanks, Chad!

**Comment by scpeters** [comment]
Yes, thanks!
