### ISSUE TITLE
release driver_common for Jade

### ISSUE THREAD

**Issue by trainman419** [ros-drivers/driver_common#8]
It's a dependency for the wge100 driver, and several other things as well.

I just released diagnostics, so this should be safe to release.

**Comment by wjwwood** [comment]
+1 It's on the list for desktop-full as well: http://wiki.ros.org/jade/Planning/Maintenance

**Comment by jack-oquin** [comment]
+1 several other drivers still use it. We could modify them to do without, but it always ends up being easier to keep releasing it.

**Comment by scpeters** [comment]
+1, `gazebo_plugins` uses `driver_base/SensorLevels` in a few places.
- https://github.com/ros-simulation/gazebo_ros_pkgs/blob/indigo-devel/gazebo_plugins/cfg/GazeboRosCamera.cfg#L6
- https://github.com/ros-simulation/gazebo_ros_pkgs/blob/indigo-devel/gazebo_plugins/cfg/GazeboRosOpenniKinect.cfg#L6
- https://github.com/ros-simulation/gazebo_ros_pkgs/blob/indigo-devel/gazebo_plugins/cfg/Hokuyo.cfg#L41

**Comment by chadrockey** [comment]
https://github.com/ros/rosdistro/pull/8083

**Comment by scpeters** [comment]
Thanks!

**Comment by trainman419** [comment]
Thanks!
